// examples/solid/src/routes/__root.tsx
/// <reference types="vite/client" />
import { HeadContent, Scripts, createRootRoute } from "@tanstack/solid-router";
import { HydrationScript } from "solid-js/web";
import type * as Solid from "solid-js";
import appCss from "../styles.css?url";
import {
  getThemeColorMetaTags,
  ThemeProvider,
  useBodyAttributes,
  useHtmlAttributes,
} from "@tanstack-themes/solid";
import { THEME_COLOR_MAP } from "../lib/themes";
import { seoLinks, seoMeta } from "../lib/seo";

export const Route = createRootRoute({
  head: () => ({
    links: [{ rel: "stylesheet", href: appCss }, ...seoLinks()],
    meta: [...getThemeColorMetaTags(THEME_COLOR_MAP), ...seoMeta()],
  }),
  shellComponent: RootDocument,
});

function RootDocument(props: { children: Solid.JSX.Element }) {
  const htmlAttributes = useHtmlAttributes();
  const bodyAttributes = useBodyAttributes();

  return (
    <html lang="en" {...htmlAttributes()}>
      <head>
        <HydrationScript />
      </head>
      <body {...bodyAttributes()}>
        <HeadContent />
        {props.children}
        <ThemeProvider themeColorLookup={THEME_COLOR_MAP} />
        <Scripts />
      </body>
    </html>
  );
}

// docs/src/routes/__root.tsx
/// <reference types="vite/client" />
import {
  createRootRoute,
  HeadContent,
  Outlet,
  Scripts,
} from "@tanstack/react-router";
import * as React from "react";
import appCss from "@/styles.css?url";
import { RootProvider } from "fumadocs-ui/provider/tanstack";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "Fumadocs on TanStack Start",
      },
    ],
    links: [{ rel: "stylesheet", href: appCss }],
  }),
  component: RootComponent,
});

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  );
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <head>
        <HeadContent />
      </head>
      <body className="flex flex-col min-h-screen">
        <RootProvider>{children}</RootProvider>
        <Scripts />
      </body>
    </html>
  );
}
