// examples/solid/src/routes/index.tsx
import { ClientOnly, createFileRoute } from "@tanstack/solid-router";
import { setTheme, setVariant, useTheme } from "@tanstack-themes/solid";
import { For } from "solid-js";
import { NativeSelect, NativeSelectOption } from "../components/native-select";
import { THEMES, type ThemeVariant } from "../lib/themes";
import { Button } from "../components/button";

export const Route = createFileRoute("/")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <main class="min-h-screen bg-background text-foreground">
      <div class="container mx-auto max-w-4xl px-4 py-12">
        <div class="space-y-8">
          <header class="text-center">
            <h1 class="text-4xl font-bold tracking-tight">
              TanStack Themes Preview
            </h1>
          </header>
          <ClientOnly>
            <div class="space-y-6">
              <VariantSelect />
              <ThemeModes />
            </div>
          </ClientOnly>
        </div>
      </div>
    </main>
  );
}

function VariantSelect() {
  const variant = useTheme((state) => state.variant);

  return (
    <div class="space-y-3 rounded-lg border border-foreground/20 bg-card p-6 shadow-md">
      <h2 class="text-lg font-semibold">Switch theme variant</h2>
      <NativeSelect
        value={variant()}
        onChange={(e) => setVariant(e.target.value as ThemeVariant)}
        class="border-foreground/20"
      >
        <For each={THEMES} fallback="Loading">
          {(theme) => (
            <NativeSelectOption value={theme}>{theme}</NativeSelectOption>
          )}
        </For>
      </NativeSelect>
    </div>
  );
}

function ThemeModes() {
  return (
    <div class="space-y-3 rounded-lg border border-foreground/20 bg-card p-6 shadow-md">
      <h2 class="text-lg font-semibold">Toggle theme mode</h2>
      <div class="flex flex-wrap gap-2">
        <Button onClick={() => setTheme("light")}>Light</Button>
        <Button onClick={() => setTheme("dark")}>Dark</Button>
        <Button onClick={() => setTheme("auto")}>System</Button>
      </div>
    </div>
  );
}

// examples/react/src/routes/index.tsx
import { createFileRoute, ClientOnly } from "@tanstack/react-router";
import { useTheme, setVariant, setTheme } from "@tanstack-themes/react";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "../components/dropdown-menu";
import { Button } from "../components/button";
import { DesktopIcon, MoonIcon, SunIcon } from "@radix-ui/react-icons";
import { NativeSelect, NativeSelectOption } from "../components/native-select";
import { ThemeVariant, THEMES } from "../lib/themes";

export const Route = createFileRoute("/")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold">Hello world!</h1>
      <ClientOnly>
        <ThemeToggle />
        <VariantSelect />
      </ClientOnly>
    </main>
  );
}

function VariantSelect() {
  const variant = useTheme((state) => state.variant);
  return (
    <NativeSelect
      value={variant}
      onChange={(e) => setVariant(e.target.value as ThemeVariant)}
    >
      {THEMES.map((theme) => (
        <NativeSelectOption key={theme} value={theme}>
          {theme}
        </NativeSelectOption>
      ))}
    </NativeSelect>
  );
}

export function ThemeToggle() {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className="[&>svg]:absolute [&>svg]:size-5 [&>svg]:scale-0"
        >
          <SunIcon className="light:scale-100! auto:scale-0!" />
          <MoonIcon className="auto:scale-0! dark:scale-100!" />
          <DesktopIcon className="auto:scale-100!" />
          <span className="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => setTheme("light")}>
          Light
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("dark")}>
          Dark
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme("auto")}>
          System
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
